### ISSUE TITLE
Please add a license to this package

### ISSUE THREAD

**Issue by davide125** [xaionaro-go/atomicmap#2]
I don't see a LICENSE file anywhere in the project nor a declaration in any of the sources. Could you please clarify what license the project is under and add one? This will make it easier to package atomicmap (and things depending on it) for Linux distributions, among other things. Thanks!

**Comment by xaionaro** [comment]
Yeah, sorry, forgot about that. Added: https://github.com/xaionaro-go/atomicmap/blob/master/LICENSE

**Comment by davide125** [comment]
Thank you!
